site_name: seer.app docs

nav:
  - Home: index.md

  - Front-End:
      - Elementos Base: frontend/base-frontend.md
      - Componentes: frontend/components-frontend.md
      - Página Home: frontend/home-frontend.md
      - Página Login e Registro: frontend/auth-frontend.md
      - Página Painel: frontend/pannel-frontend.md
      - Página Relatórios: frontend/report_app_frontend.md
      - Configurações: frontend/settings-frontend.md
      - Suporte: frontend/support-frontend.md
      - Notificações: frontend/notifications-frontend.md

  - Back-End:
      - Login: backend/views/login.md
      - Onboarding: backend/views/onboarding.md
      - Painel: backend/views/panel.md
      - Relatórios: backend/views/relatorios.md
      - Notificações: backend/views/notifications.md
      - Preferências: backend/views/preferencias.md
      - Página Relatórios: backend/report_app_backend.md

  - Banco de Dados: 
      - Página Relatórios: db/report_app_database.md

theme:
  name: material
  language: pt-BR
  palette:
    scheme: default
    primary: teal
    accent: lime
  font:
    text: 'Exo 2'
    code: 'Fira Code'
  favicon: images/favicon.png
  logo: images/logo.png 
  

  features:
    - navigation.expand
    - navigation.sections
    - search.highlight
    - content.code.copy

extra_css:
  - css/extra.css
